name: "picko_bot"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_picko
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - 27019:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picko_bot_app
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://mongodb:27017/picko
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

volumes:
  mongo-data:

networks:
  app-network:
