name: "picko_bot"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picko_bot_app
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://host.docker.internal:27017/picko
    restart: always
